include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**/generated_plugin_registrant.dart'
    - '**.graphql.dart'
    - '**.config.dart'

linter:
  rules:
    prefer_single_quotes: true
    avoid_slow_async_io: true
    prefer_relative_imports: true
    avoid_dynamic_calls: true
    cancel_subscriptions: true
    discarded_futures: true
    unnecessary_statements: true
    always_declare_return_types: true
    avoid_annotating_with_dynamic: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    avoid_redundant_argument_values: true
    only_throw_errors: true
    prefer_constructors_over_static_methods: true
    prefer_expression_function_bodies: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_null_aware_method_calls: true
    require_trailing_commas: true
    sort_constructors_first: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    use_enums: true
    unnecessary_null_checks: true
    unnecessary_raw_strings: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true


