targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - $package$
    builders:
      graphql_codegen:
        options:
          addTypenameExcludedPaths:
            - subscription
          extraKeywords:
            - String
          clients:
            - graphql
          assetsPath: graphql/**
          outputDirectory: /lib/graphql
          scalars:
            jsonb:
              type: Map<String, dynamic>
            json:
              type: Map<String, dynamic>
            uuid:
              type: String
            timestamptz:
              type: DateTime
            timestamp:
              type: DateTime
            numeric:
              type: double
            bigint:
              type: int
