version: '2.3'

services:
  backend:
    image: selecthackatum/backend:latest
    container_name: backend
    expose:
    - 3000
    restart: always
    networks:
      - hackatum
    labels:
      caddy: backend.stephan.vm.selectcode.io
      caddy.reverse_proxy: "{{upstreams 3000}}"
      com.centurylinklabs.watchtower.enable: "true"
networks:
  hackatum:
    external: true