name: Build & Publish backend Docker image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: selecthackatum
          password: dckr_pat_E40DfKiJChZJ3mTgKChbr6basYI
      -
        name: Change to backend directory
        run: cd backend
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./backend/Dockerfile
          context: ./backend
          push: true
          tags: selecthackatum/backend:latest